<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- Paket za SQLite -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
		<!-- Paket za Entity Framework Tools (za migracije) -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\DatabaseEntityLib\DatabaseEntityLib.csproj" />
	</ItemGroup>


</Project>